sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install python-pip python2.7-dev libxext-dev python-qt4 qt4-dev-tools build-essential 
  - sudo apt-get install qt4-dev-tools qt4-doc qt4-qtconfig qt4-demos qt4-designer 
  - sudo apt-get install libqwt5-qt4 libqwt5-qt4-dev
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/sip/sip-4.14.1/sip-4.14.1.tar.gz
  - tar -xvf sip-4.14.1.tar.gz
  - cd sip-4.14.1
  - python configure.py
  - make -j 2
  - sudo make install
  - cd ..
  - curl -L -O http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.9.5/PyQt-x11-gpl-4.9.5.tar.gz
  - tar -xvf PyQt-x11-gpl-4.9.5.tar.gz
  - cd PyQt-x11-gpl-4.9.5
  - python configure.py --confirm-license
  - make -j 2
  - sudo make install
  - cd ..
  - curl -L -O http://apps.ankiweb.net/downloads/current/anki-2.0.52-source.tgz
  - tar -xvf anki-2.0.52-source.tgz
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script:
  - mv src addons
  - python runanki -b .
